src/Entity/Servers.php
<?php

namespace App\Entity;

use App\Repository\ServersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ServersRepository::class)
 */
class Servers
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity=AccountsManagers::class, inversedBy="adminServers")
     */
    private $adminManager;

    /**
     * @ORM\ManyToOne(targetEntity=AccountsManagers::class, inversedBy="technicalServers")
     */
    private $technicalManager;

    /**
     * @ORM\ManyToOne(targetEntity=AccountsManagers::class, inversedBy="billingServers")
     */
    private $billingManager;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ipAdress;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $projectPublicCloud;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $model;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $region;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $dataCenter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $subscription;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $operatingSystem;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cpu;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ram;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $discSpace;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $extraDisc;

    /**
     * @ORM\OneToMany(targetEntity=Projects::class, mappedBy="server")
     */
    private $projects;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $apache_nginx;

    /**
     * @ORM\ManyToOne(targetEntity=Clients::class, inversedBy="servers")
     */
    private $client;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $identifier;

   

    public function __construct()
    {
        $this->projects = new ArrayCollection();
    }
    
    public function __toString() {
        return (String) $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAdminManager(): ?AccountsManagers
    {
        return $this->adminManager;
    }

    public function setAdminManager(?AccountsManagers $adminManager): self
    {
        $this->adminManager = $adminManager;

        return $this;
    }

    public function getTechnicalManager(): ?AccountsManagers
    {
        return $this->technicalManager;
    }

    public function setTechnicalManager(?AccountsManagers $technicalManager): self
    {
        $this->technicalManager = $technicalManager;

        return $this;
    }

    public function getBillingManager(): ?AccountsManagers
    {
        return $this->billingManager;
    }

    public function setBillingManager(?AccountsManagers $billingManager): self
    {
        $this->billingManager = $billingManager;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getIpAdress(): ?string
    {
        return $this->ipAdress;
    }

    public function setIpAdress(string $ipAdress): self
    {
        $this->ipAdress = $ipAdress;

        return $this;
    }

    public function getProjectPublicCloud(): ?string
    {
        return $this->projectPublicCloud;
    }

    public function setProjectPublicCloud(string $projectPublicCloud): self
    {
        $this->projectPublicCloud = $projectPublicCloud;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(string $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getDataCenter(): ?string
    {
        return $this->dataCenter;
    }

    public function setDataCenter(string $dataCenter): self
    {
        $this->dataCenter = $dataCenter;

        return $this;
    }

    public function getSubscription(): ?string
    {
        return $this->subscription;
    }

    public function setSubscription(string $subscription): self
    {
        $this->subscription = $subscription;

        return $this;
    }

    public function getOperatingSystem(): ?string
    {
        return $this->operatingSystem;
    }

    public function setOperatingSystem(string $operatingSystem): self
    {
        $this->operatingSystem = $operatingSystem;

        return $this;
    }
    
    public function getCpu(): ?string
    {
        return $this->cpu;
    }

    public function setCpu(string $cpu): self
    {
        $this->cpu = $cpu;

        return $this;
    }

    public function getRam(): ?string
    {
        return $this->ram;
    }

    public function setRam(string $ram): self
    {
        $this->ram = $ram;

        return $this;
    }

    public function getDiscSpace(): ?string
    {
        return $this->discSpace;
    }

    public function setDiscSpace(string $discSpace): self
    {
        $this->discSpace = $discSpace;

        return $this;
    }

    public function getExtraDisc(): ?string
    {
        return $this->extraDisc;
    }

    public function setExtraDisc(string $extraDisc): self
    {
        $this->extraDisc = $extraDisc;

        return $this;
    }

    /**
     * @return Collection|Projects[]
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Projects $project): self
    {
        if (!$this->projects->contains($project)) {
            $this->projects[] = $project;
            $project->setServer($this);
        }

        return $this;
    }

    public function removeProject(Projects $project): self
    {
        if ($this->projects->removeElement($project)) {
            // set the owning side to null (unless already changed)
            if ($project->getServer() === $this) {
                $project->setServer(null);
            }
        }

        return $this;
    }

    public function getApacheNginx(): ?string
    {
        return $this->apache_nginx;
    }

    public function setApacheNginx(string $apache_nginx): self
    {
        $this->apache_nginx = $apache_nginx;

        return $this;
    }

    public function getClient(): ?Clients
    {
        return $this->client;
    }

    public function setClient(?Clients $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getIdentifier(): ?string
    {
        return $this->identifier;
    }

    public function setIdentifier(string $identifier): self
    {
        $this->identifier = $identifier;

        return $this;
    }
}

src/Form/ServersType.php
<?php

namespace App\Form;

use App\Entity\Servers;
use App\Entity\AccountsManagers;
use App\Repository\AccountsManagersRepository;
use App\Entity\Projects;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\ChoiceList\ChoiceList;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;

class ServersType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
                ->add('identifier')
                ->add('name')
                ->add('type')
                ->add('ipAdress')
                ->add('projectPublicCloud')
                ->add('model')
                ->add('region')
                ->add('dataCenter')
                ->add('subscription')
                ->add('operatingSystem')
                ->add('cpu')
                ->add('ram')
                ->add('discSpace')
                ->add('extraDisc')
                ->add('apache_nginx', ChoiceType::class, [
                    'choices' => [
                        'Apache' => 'apache',
                        'Nginx' => 'nginx'
                    ],
                    'label' => FALSE,
                    'attr' => [
                        'class' => 'form-control'
                    ]
                ])
                ->add('adminManager', EntityType::class, [
                    'class' => AccountsManagers::class,
                    'query_builder' => function (AccountsManagersRepository $er) {
                        return $er->createQueryBuilder('u')
                                ->andWhere('u.function = :val')
                                ->setParameter('val', 'adminManager');
                    },
                ])
                ->add('technicalManager', EntityType::class, [
                    'class' => AccountsManagers::class,
                    'query_builder' => function (AccountsManagersRepository $er) {
                        return $er->createQueryBuilder('u')
                                ->andWhere('u.function = :val')
                                ->setParameter('val', 'technicalManager');
                    },
                ])
                ->add('billingManager', EntityType::class, [
                    'class' => AccountsManagers::class,
                    'query_builder' => function (AccountsManagersRepository $er) {
                        return $er->createQueryBuilder('u')
                                ->andWhere('u.function = :val')
                                ->setParameter('val', 'billingManager');
                    },
                ])
                ->add('client')
        ;
    }

    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => Servers::class,
        ]);
    }

}

src/Controller/ServersController.php
<?php

namespace App\Controller;

use App\Entity\Servers;
use App\Form\ServersType;
use App\Repository\ServersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/servers")
 */
class ServersController extends AbstractController {

    /**
     * @Route("/", name="servers_index", methods={"GET","POST"})
     */
    public function index(
            ServersRepository $serversRepository,
            Request $request
    ): Response {
        $servers = $serversRepository->findAll();
        $server = new Servers();
        $form = $this->createForm(ServersType::class, $server);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            foreach ($servers as $s) {
                if ($server->getIdentifier() === $s->getIdentifier()) {
                    $this->addFlash('error', 'the id '.$server->getIdentifier() . ' is already in use try with another one! ');
                    return $this->redirectToRoute('servers_index', [], Response::HTTP_SEE_OTHER);
                    die();
                }
            }
            $entityManager->persist($server);
            $entityManager->flush();
            $this->addFlash('success', $server->getName() . ' Successfuly added! ');
            return $this->redirectToRoute('servers_index', [], Response::HTTP_SEE_OTHER);
        }


        return $this->render('servers/index.html.twig', [
                    'servers' => $servers,
                    'server' => $server,
                    'form' => $form->createView(),
        ]);
    }
    
    /**
     * @Route("/{id}", name="servers_show", methods={"GET"})
     */
    public function show(Servers $server): Response
    {
        return $this->render('servers/show.html.twig', [
            'server' => $server,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="servers_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Servers $server): Response {
        $form = $this->createForm(ServersType::class, $server);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', $server->getName() . ' Successfuly deleted! ');
            return $this->redirectToRoute('servers_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('servers/edit.html.twig', [
                    'server' => $server,
                    'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="servers_delete", methods={"POST"})
     */
    public function delete(Request $request, Servers $server): Response {
        if ($this->isCsrfTokenValid('delete' . $server->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($server);
            $entityManager->flush();
            $this->addFlash('success', $server->getName() . ' Successfuly deleted! ');
        }

        return $this->redirectToRoute('servers_index', [], Response::HTTP_SEE_OTHER);
    }

}

templates/servers/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Servers{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/bower_components/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/bower_components/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/component.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/pages/notification/notification.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/bower_components/animate.css/css/animate.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/pages/j-pro/css/demo.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/pages/j-pro/css/font-awesome.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/pages/j-pro/css/j-pro-modern.css') }}">

{% endblock %}

{% block body %}
    {% for message in app.flashes('success') %}
        <ul class="notifications" id="alert">
            <li>
                <button hidden id="alert_btn_success" class="btn btn-primary waves-effect" data-type="success" data-animation-in="animated bounceInRight" data-animation-out="animated bounceOutRight" data-title="Success! " data-message="{{ message }}">Bounce In Right</button>
            </li>
        </ul>
    {% endfor %}
    <div class="page-wrapper">
        <div class="page-header">
            <div class="page-header-title">
                <h4>Servers</h4>
            </div>
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="{{ path('dashboard') }}">
                            <i class="icofont icofont-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="#!">Pages</a>
                    </li>
                    <li class="breadcrumb-item"><a href="#!">Servers</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="page-body">
            <div class="row">
                <div class="col col-lg-12">
                    <div class="card ">
                        <div class="card-header">
                            <h5>Details of server: </h5><label class="text-info"><strong>{{ server.name }}</strong></label>
                            <a class="badge badge-info btn f-right"
                               href="{{ path('servers_index') }}">
                                <i class="fa fa-arrow-left"></i>
                            </a>
                        </div>
                        <div class="card-block">
                            <div class="row">
                                <div class="col-lg-12 col-xl-12">                                       
                                    <div class="row">
                                        <div class="col-lg-4 users-card">
                                            <div class="card user-card">
                                                <div class="card-header">
                                                    General informations
                                                </div>
                                                <div class="card-block">
                                                    <div class="row">
                                                        <div class="col-lg-12">
                                                            <ul>
                                                                <li>Client: {{ server.client }}</li>
                                                                <li>Type: {{ server.type }}</li>
                                                                <li>Model: {{ server.model }}</li>
                                                                <li>region: {{ server.region }}</li>
                                                                <li>Data center: {{ server.dataCenter }}</li>
                                                                <li>Subscrition: {{ server.subscription }}</li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        
                                        <div class="col-lg-4 users-card">
                                            <div class="card user-card">
                                                <div class="card-header">
                                                    Technical informations
                                                </div>
                                                <div class="card-block">
                                                    <div class="row">
                                                        <div class="col-lg-12">
                                                            <ul>
                                                                <li>IP Adress: {{ server.ipAdress }}</li>
                                                                <li>Operating system: {{ server.operatingSystem }}</li>
                                                                <li>CPU: {{ server.cpu }}</li>
                                                                <li>RAM: {{ server.ram }}</li>
                                                                <li>Disk: {{ server.discSpace }}</li>
                                                                <li>Extra disk: {{ server.extraDisc }}</li>
                                                                <li>Embedded WEB server: {{ server.apacheNginx }}</li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                                            
                                        <div class="col-lg-4 users-card">
                                            <div class="card user-card">
                                                <div class="card-header">
                                                    Managers
                                                </div>
                                                <div class="card-block">
                                                    <div class="row">
                                                        <div class="col-lg-12">
                                                            <ul>
                                                                <li>Admin: {{ server.adminManager }}</li>
                                                                <li>Technical manager: {{ server.technicalManager }}</li>
                                                                <li>Billing manager: {{ server.billingManager }}</li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                                            
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('assets/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/bower_components/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/bower_components/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('assets/bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/pages/data-table/js/data-table-custom.js') }}"></script>

    <script type="text/javascript" src="{{ asset('assets/bower_components/sweetalert/js/sweetalert.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/modal.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/modalEffects.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/classie.js') }}"></script>

    <script>
        $("#alert").ready(function(){
            $("#alert_btn_success").click();
        });
    </script>

{% endblock %}